In [16]:
import pandas as pd
from datetime import datetime
df1 = pd.concat(pd.read_excel('PV_firstRealease.xlsx', sheet_name=None), ignore_index=True)
df1.head()

,Hour,Starting minute (inclussive),Ending minute (exclussive),Generated power,TemperatureC,DewpointC,PressurehPa,WindDirectionDegrees,WindSpeedKMH,WindSpeedGustKMH,Humidity,HourlyPrecipMM,dailyrainMM,SolarRadiationWatts_m2
0,0,0,5,0,0,0,0,0,0,0,0,0,0,0
1,0,5,10,0,0,0,0,0,0,0,0,0,0,0
2,0,10,15,0,11,8,1021,114,1,17,83,0,0,0
3,0,15,20,0,11,8,1021,134,12,17,83,0,0,0
4,0,20,25,0,11,8,1021,128,8,17,83,0,0,0

In [17]:
def remove_dataset_ouliers(dataset):
        list_outliers_index=[]
        for c in dataset:
            if type(c[0])!=str:
                list_outliers_index.extend(column_outliers(dataset, c))
        cleaned_dataset=remove_outliers(dataset, list_outliers_index)
        return cleaned_dataset

def column_outliers(df,c):
    q1=df[c].quantile(0.25)
    q3=df[c].quantile(0.75)
    iqr=q3-q1
    lower_bound=q1-4*iqr
    upper_bound=q3+4*iqr
    o = df.index[(df[c]<lower_bound) | (df[c]>upper_bound)]
    return o

def remove_outliers(df, outliers):
    outliers=sorted(set(outliers))
    df=df.drop(outliers)
    return df

In [105]:
df=df1
df["DateTime"] = df['Hour'].astype(str) +":"+ df["Starting minute (inclussive)"].astype(str)
df=df.drop(columns='Hour')
df=df.drop(columns='Ending minute (exclussive)')
df=df.drop(columns='Starting minute (inclussive)')
# df['DateTime'] = df['DateTime'] + ':00'
# convert to timedelta
df['DateTime'] = pd.to_datetime(df['DateTime'], format='%H:%M')
# df['DateTime'] = pd.to_timedelta(df['DateTime'])
# df["DateTime"] = df["DateTime"].dt.strftime("%H:%M")
print(type(df["DateTime"][0]))
first_column=df.pop("DateTime")
df.insert(0, "DateTime", first_column)
# get the index
idx = df.index
print('ind',idx)
df = df.rename_axis('index')
df
df.set_index("DateTime",append=True, inplace=True)
# # print(df.columns.to_list())
df=df.resample('15min',level='DateTime').mean()
# # df
df.reset_index(inplace=True)
# df
df['DateTime'] = pd.to_datetime(df['DateTime'], format='%H:%M').dt.time
df.head(6)

<class 'pandas._libs.tslibs.timestamps.Timestamp'>
ind RangeIndex(start=0, stop=315360, step=1)

,DateTime,Generated power,TemperatureC,DewpointC,PressurehPa,WindDirectionDegrees,WindSpeedKMH,WindSpeedGustKMH,Humidity,HourlyPrecipMM,dailyrainMM,SolarRadiationWatts_m2
0,00:00:00,44.968037,9.054186,7.166210,605.649315,138.004871,1.432877,0.852055,89.846271,0.083714,0.894064,40.079452
1,00:15:00,44.968037,13.649924,10.790563,921.055099,207.744901,2.062709,1.316591,135.483105,0.618874,0.043227,63.839269
2,00:30:00,44.968037,13.492237,10.680974,916.512024,206.245358,2.084323,1.371081,134.102283,2.007306,0.062100,87.779604
3,00:45:00,44.968037,13.392390,10.618265,913.996347,204.028311,1.948554,1.215221,134.036225,2.006088,0.084932,111.719635
4,01:00:00,44.968037,13.286758,10.546423,908.417352,201.802435,2.078843,0.970472,134.463927,1.020700,0.098021,91.771081
5,01:15:00,44.968037,13.277930,10.553729,910.983257,202.063014,1.944597,1.005784,135.170167,0.600913,0.120244,71.827397

In [86]:
df1.head(12)
# df_no_out=remove_dataset_ouliers(df)
# print('Before', len(df), 'After', len(df_no_out), 'Difference',(len(df)-len(df_no_out)))

,Hour,Starting minute (inclussive),Ending minute (exclussive),Generated power,TemperatureC,DewpointC,PressurehPa,WindDirectionDegrees,WindSpeedKMH,WindSpeedGustKMH,Humidity,HourlyPrecipMM,dailyrainMM,SolarRadiationWatts_m2,DateTime
0,0,0,5,0,0,0,0,0,0,0,0,0,0,0,0:0
1,0,5,10,0,0,0,0,0,0,0,0,0,0,0,0:5
2,0,10,15,0,11,8,1021,114,1,17,83,0,0,0,0:10
3,0,15,20,0,11,8,1021,134,12,17,83,0,0,0,0:15
4,0,20,25,0,11,8,1021,128,8,17,83,0,0,0,0:20
5,0,25,30,0,11,8,1021,123,6,17,83,0,0,0,0:25
6,0,30,35,0,11,8,1021,143,0,20,83,0,0,0,0:30
7,0,35,40,0,11,8,1021,128,0,20,83,0,0,0,0:35
8,0,40,45,0,11,8,1021,129,4,17,83,0,0,0,0:40
9,0,45,50,0,11,8,1021,136,4,14,83,0,0,0,0:45
10,0,50,55,0,11,8,1021,122,1,12,82,0,0,0,0:50
11,0,55,60,0,11,8,1021,125,4,11,82,0,0,0,0:55